### ISSUE TITLE
consider Mapbox GL

### ISSUE THREAD

**Issue by incanus** [DiogoAndre/ProMotion-mapbox#3]
This is great! I don't use ProMotion (I'm a long-time Cocoa dev and work at Mapbox) but the whole system, and this gem, look great. 

You might consider moving to [Mapbox GL](https://www.mapbox.com/mapbox-gl-ios/), which is: 
1. The future of Mapbox's mobile stack
2. More like Apple's MapKit than our iOS SDK is
3. Hardware-accelerated OpenGL-based rendering

Let me know if I can help in any way!

**Comment by DiogoAndre** [comment]
Thanks for you comment @incanus !  I have plans to move the gem to use Mapbox GL. I actually stopped working on the current version when I saw that Mapbox GL was close to being released. I just have to find some time to do it, though.  From what I saw, it shouldn't be too hard.

Thanks!

**Comment by DiogoAndre** [comment]
Thanks again @incanus for the push to do this. ProMotion-mapbox is now using Mapbox GL starting with fd759b651efe9341e67ccf1ad042c093331896b4. 

Cheers!

**Comment by incanus** [comment]
:tada:
